import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {getUser} from "@/actions/auth/user.action";
import AuthHeader from "@/components/AuthHeader";
import JinHeader from "@/components/JinHeader";
import HomeContainer from "@/app/(site)/HomeContainer";
import 'react-quill/dist/quill.snow.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const user = await getUser({serverComponent: true});
    return (
        <html lang="en">
        <body className={inter.className}>
        {/*<AuthHeader user={user}/>*/}
        <div className='relative flex size-full min-h-screen flex-col bg-white group/design-root overflow-x-hidden'>
            <div className='layout-container flex h-full grow flex-col'>
                <JinHeader/>
                {children}
            </div>
        </div>
        </body>
        </html>
    )
}
